apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: blackbox-exporter
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 9.0.0

    helm:
      values: |
        service:
          port: 9115

        config:
          modules:
            http_2xx:
              prober: http
              timeout: 10s
              http:
                preferred_ip_protocol: ip4

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true