apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: platform-alerts
  namespace: monitoring

spec:
  groups:

    - name: kubernetes.rules
      rules:

        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Node Not Ready
            description: Node {{ $labels.node }} is not ready

        - alert: PodCrashLoopBackOff
          expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Pod CrashLoopBackOff
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} is crashing

        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_status_replicas_available < kube_deployment_spec_replicas
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Deployment Replicas Mismatch
            description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} missing replicas

        - alert: HighCPUUsage
          expr: 100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High CPU Usage
            description: CPU usage above 80%

        - alert: HighMemoryUsage
          expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: High Memory Usage
            description: Memory usage above 85%

        - alert: PVCUsageHigh
          expr: 100 * (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) > 80
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: PVC Usage High
            description: PVC usage above 80%

        - alert: ExternalEndpointDown
          expr: probe_success == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: Endpoint Down
            description: "{{ $labels.instance }} is unreachable"