crds:
  enabled: false

grafana:
  enabled: true

  persistence:
    enabled: true
    storageClassName: gp3
    size: 10Gi

prometheus:
  prometheusSpec:
    probeSelectorNilUsesHelmValues: false
    probeSelector: {}

    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  enabled: true

kubeStateMetrics:
  enabled: true

defaultRules:
  create: true