apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: grafana-admin-secret
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore

  target:
    name: grafana-admin-secret

  data:
    - secretKey: admin-password
      remoteRef:
        key: /platform/grafana/admin-password