apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: jenkins-admin-secret
  namespace: jenkins

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore

  target:
    name: jenkins-admin-secret

  data:
    - secretKey: admin-password
      remoteRef:
        key: /platform/jenkins/admin-password