apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml
  - grafana-secret.yaml
  - jenkins-secret.yaml
  - sonarqube-secret.yaml
  - slack-webhook-secret.yaml