apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: slack-webhook
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore

  target:
    name: slack-webhook

  data:
    - secretKey: webhook-url
      remoteRef:
        key: /platform/monitoring/slack-webhook