apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: sonarqube-admin-secret
  namespace: sonarqube

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore

  target:
    name: sonarqube-admin-secret
    creationPolicy: Owner

  data:
    - secretKey: admin-user
      remoteRef:
        key: /platform/sonarqube/admin-user

    - secretKey: admin-password
      remoteRef:
        key: /platform/sonarqube/admin-password