installCRDs: true

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: external-secrets

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::719572784863:role/rk-labs-external-secrets