apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass

metadata:
  name: default

spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: KarpenterNodeRole-rk-labs-eks

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: rk-labs-eks

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: rk-labs-eks

  tags:
    karpenter.sh/discovery: rk-labs-eks