apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass

metadata:
  name: default

spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: dev-eks-node-role

  securityGroupSelectorTerms:
    - id: sg-024b98e4d3059b63a
    - id: sg-0d6cc236e13f23f69

  subnetSelectorTerms:
    - id: subnet-04d424b7904c39aa5
    - id: subnet-0713d9dfcf0839d4d
    - id: subnet-08f7b3ebfccf0c50b

  tags:
    karpenter.sh/discovery: dev-eks