apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - policies/disallow-latest-tag.yaml
  - policies/require-limits.yaml
  - policies/require-probes.yaml
  - policies/disallow-privileged.yaml