deploymentMode: SingleBinary

singleBinary:
  replicas: 1

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

persistence:
  enabled: true
  storageClass: gp3
  size: 20Gi

gateway:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true