apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: job-bot
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: job-bot=719572784863.dkr.ecr.us-east-1.amazonaws.com/job-bot
    argocd-image-updater.argoproj.io/job-bot.force-update: "true"
    argocd-image-updater.argoproj.io/job-bot.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default

  source:
    repoURL: https://github.com/RKvamsi-lab/ops-services.git

    targetRevision: main

    path: apps/job-bot

  destination:
    server: https://kubernetes.default.svc

    namespace: job-bot

  syncPolicy:
    automated:
      prune: true

      selfHeal: true

    syncOptions:
      - CreateNamespace=true