apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: karpenter
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://charts.karpenter.sh
    chart: karpenter
    targetRevision: 0.16.3

    helm:
      values: |
        serviceAccount:
          create: true
          name: karpenter

          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::719572784863:role/karpenter-controller-role

        settings:
          clusterName: dev-eks
          clusterEndpoint: https://CE67A46B906F0842C513E709193ABB2B.gr7.us-east-1.eks.amazonaws.com

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true