apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-api.yaml
  - external-secrets.yaml
  - frontend-ui.yaml
  - grafana.yaml
  - jenkins.yaml
  - karpenter.yaml
  - karpenter-resources.yaml
  - loki.yaml
  - nginx.yaml
  - platform-ingress.yaml
  - prometheus.yaml
  - prometheus-resources.yaml
  - sonarqube.yaml
  - vault.yaml
  - velero.yaml
  - whoami.yaml
  - external-secrets.yaml
  - external-secrets-resources.yaml