apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vault
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.0

    helm:
      values: |
        server:
          enabled: true

          replicas: 1

          serviceAccount:
            create: true

            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::719572784863:role/dev-vault-irsa

          extraEnvironmentVars:
            AWS_REGION: us-east-1

          standalone:
            enabled: true

            config: |
              ui = true

              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }

              storage "file" {
                path = "/vault/data"
              }

              seal "awskms" {
                region     = "us-east-1"
                kms_key_id = "53267b27-93d7-4ea3-b187-85291ffecb4d"
              }

          dataStorage:
            enabled: true
            storageClass: gp3
            size: 20Gi

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 1000m
              memory: 2Gi

        ui:
          enabled: true

        injector:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'