apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vault
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.0

    helm:
      values: |
        server:
          enabled: true

          replicas: 1

          standalone:
            enabled: true

          dataStorage:
            enabled: true
            storageClass: gp3
            size: 20Gi

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 1000m
              memory: 2Gi

        ui:
          enabled: true

        injector:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true


  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: vault-agent-injector-cfg

    jqPathExpressions:
      - '.webhooks[].clientConfig.caBundle'