apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: whoami
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: whoami=719572784863.dkr.ecr.us-east-1.amazonaws.com/whoami

    argocd-image-updater.argoproj.io/whoami.update-strategy: newest-build

    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default

  source:
    repoURL: https://github.com/RKvamsi-lab/ops-services.git
    targetRevision: main
    path: apps/whoami

  destination:
    server: https://kubernetes.default.svc
    namespace: whoami

  syncPolicy:
    automated:
      prune: true
      selfHeal: true