replicas: 1

podDisruptionBudget:
  enabled: true
  minAvailable: 1

persistence:
  enabled: true
  type: pvc
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  size: 10Gi

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

grafana.ini:
  server:
    root_url: https://grafana.rk-labs.xyz

ingress:
  enabled: false