apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default

spec:
  amiFamily: AL2023

  role: dev-eks-node-role

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: dev-eks

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: dev-eks

  tags:
    Environment: dev
    ManagedBy: Karpenter