apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
<<<<<<< HEAD:platform/prometheus/kustomization.yaml
  - namespace.yaml
  - ingress.yaml
  - helm-release.yaml
=======
  - ec2nodeclass.yaml
  - nodepool.yaml
>>>>>>> backup/stable-0fc667e:platform/karpenter/kustomization.yaml
