community:
  enabled: true

monitoringPasscode: "SonarQubeMonitor123"

persistence:
  enabled: true
  storageClass: gp3
  size: 20Gi

service:
  type: ClusterIP

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

ingress:
  enabled: false