apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: backend-api

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: backend-api-secret

  data:
    - secretKey: github-token

      remoteRef:
        key: github-token
        property: token