apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-api
  namespace: backend-api

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: backend-api-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: backend-api
        property: DATABASE_URL