apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - external-secret.yaml
images:
  - name: 719572784863.dkr.ecr.us-east-1.amazonaws.com/backend-api
    newTag: latest
