apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: job-bot
  namespace: job-bot

spec:

  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm

  target:
    name: job-bot-secret

  data:
    - secretKey: config
      remoteRef:
        key: /dev/job-bot