apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: 719572784863.dkr.ecr.us-east-1.amazonaws.com/frontend-ui
    newTag: 978415faa5c89b3b513d0343250ecb2232cbb5a3